// angry01 animation for Adafruit SSD1306/SH1106
// Generated by make_face.py - 12 frames @ 10fps
// Format: Adafruit_GFX bitmap (MSB first)
// Display: 128x64 OLED

#ifndef ANGRY01_H
#define ANGRY01_H

#include <Arduino.h>

// Animation properties
#define ANGRY01_FRAME_COUNT 12
#define ANGRY01_FPS 10
#define ANGRY01_FRAME_DELAY 100  // ms per frame

// Frame data lives in angry01.cpp (separate translation unit for fast rebuilds)
extern const unsigned char* const angry01_frames[];

#endif
