// coffee01 animation for Adafruit SSD1306/SH1106
// Generated by make_face.py - 14 frames @ 10fps
// Format: Adafruit_GFX bitmap (MSB first)
// Display: 128x64 OLED

#ifndef COFFEE01_H
#define COFFEE01_H

#include <Arduino.h>

// Animation properties
#define COFFEE01_FRAME_COUNT 14
#define COFFEE01_FPS 10
#define COFFEE01_FRAME_DELAY 100  // ms per frame

// Frame data lives in coffee01.cpp (separate translation unit for fast rebuilds)
extern const unsigned char* const coffee01_frames[];

#endif
