// mochi_happy01 animation for Adafruit SSD1306/SH1106
// Generated by make_face.py - 14 frames @ 12fps
// Format: Adafruit_GFX bitmap (MSB first)
// Display: 128x64 OLED

#ifndef MOCHI_HAPPY01_H
#define MOCHI_HAPPY01_H

#include <Arduino.h>

// Animation properties
#define MOCHI_HAPPY01_FRAME_COUNT 14
#define MOCHI_HAPPY01_FPS 12
#define MOCHI_HAPPY01_FRAME_DELAY 83  // ms per frame

// Frame data lives in mochi_happy01.cpp (separate translation unit for fast rebuilds)
extern const unsigned char* const mochi_happy01_frames[];

#endif
