// sweat01 animation for Adafruit SSD1306/SH1106
// Generated by make_face.py - 14 frames @ 10fps
// Format: Adafruit_GFX bitmap (MSB first)
// Display: 128x64 OLED

#ifndef SWEAT01_H
#define SWEAT01_H

#include <Arduino.h>

// Animation properties
#define SWEAT01_FRAME_COUNT 14
#define SWEAT01_FPS 10
#define SWEAT01_FRAME_DELAY 100  // ms per frame

// Frame data lives in sweat01.cpp (separate translation unit for fast rebuilds)
extern const unsigned char* const sweat01_frames[];

#endif
