// upiir_big_smile01 animation for Adafruit SSD1306/SH1106
// Generated by make_face.py - 18 frames @ 12fps
// Format: Adafruit_GFX bitmap (MSB first)
// Display: 128x64 OLED

#ifndef UPIIR_BIG_SMILE01_H
#define UPIIR_BIG_SMILE01_H

#include <Arduino.h>

// Animation properties
#define UPIIR_BIG_SMILE01_FRAME_COUNT 18
#define UPIIR_BIG_SMILE01_FPS 12
#define UPIIR_BIG_SMILE01_FRAME_DELAY 83  // ms per frame

// Frame data lives in upiir_big_smile01.cpp (separate translation unit for fast rebuilds)
extern const unsigned char* const upiir_big_smile01_frames[];

#endif
